ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "onVacation" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "assignedShopperAt" TIMESTAMP(3);
ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "fidelized" BOOLEAN NOT NULL DEFAULT false;
